# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: express-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: express-app
#   template:
#     metadata:
#       labels:
#         app: express-app
#     spec:
#       containers:
#       - name: express-app
#         image: skumark123/my-sample-app:latest
#         ports:
#         - containerPort: 3000
#       # Tell EKS to run this pod on Fargate
#       nodeSelector:
#         eks.amazonaws.com/compute-type: fargate


apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
      - name: express-app
        image: DOCKER_USER/my-sample-app:replace-me   # will be updated by kubectl set image
        ports:
        - containerPort: 3000
    nodeSelector:
        eks.amazonaws.com/compute-type: fargate      
