name: CI pipeline

on:
   push:
      branches: [ "main" ]

   workflow_dispatch: 

jobs:
    build:
        runs-on: ubuntu-latest
        env:
         PORT: ${{ secrets.PORT }}
        strategy:
            matrix:
                node-version: [  18 ]

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: SetUp Node.js ${{matrix.node-version}}
            uses: actions/setup-node@v4
            with:
              node-version: ${{matrix.node-version}}

          - name: Install Dependencies
            run: npm i

          - name: Build App
            run: echo "Build step done (for express app nothing to compile)"

    test:
        runs-on: "ubuntu-latest"
        env:
         PORT: ${{ secrets.PORT }} 
        needs: build
        strategy:
            matrix:
                node-version: [ 18 ]
         
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Node.js ${{matrix.node-version}}   
              uses: actions/setup-node@v4
              with:
                node-version: ${{matrix.node-version}}   

            - name: Install dependencies
              run: npm i    
                
            - name: Run tests
              run: npm test   
    deploy:
        runs-on: ubuntu-latest
        env:
         PORT: ${{ secrets.PORT }}
        needs: test
        
        steps:
           - name: Checkout Repository
             uses: actions/checkout@v4
          
           - name: List repo files
             run: ls -R
  
           - name: Login to Docker Hub
             uses: docker/login-action@v2
             with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
             
           - name: Build Docker Image
             run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-sample-app:latest -f Dockerfile .

           - name: Push Docker Image
             run: docker push ${{secrets.DOCKER_USERNAME}}/my-sample-app:latest


        
        



